package test.model;
// Generated Jun 10, 2024, 11:19:57 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * Bankaccount generated by hbm2java
 */
public class Bankaccount implements java.io.Serializable {

	private Long accNo;
	private Double balance;
	private Integer count;
	private String holderName;
	private Date lastUpdated;
	private Date openingDate;
	private String type;

	public Bankaccount() {
	}

	public Bankaccount(Double balance, Integer count, String holderName, Date lastUpdated, Date openingDate,
			String type) {
		this.balance = balance;
		this.count = count;
		this.holderName = holderName;
		this.lastUpdated = lastUpdated;
		this.openingDate = openingDate;
		this.type = type;
	}

	public Long getAccNo() {
		return this.accNo;
	}

	public void setAccNo(Long accNo) {
		this.accNo = accNo;
	}

	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public String getHolderName() {
		return this.holderName;
	}

	public void setHolderName(String holderName) {
		this.holderName = holderName;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public Date getOpeningDate() {
		return this.openingDate;
	}

	public void setOpeningDate(Date openingDate) {
		this.openingDate = openingDate;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
